### PR TITLE
Switch from terms facet to aggregations

### PR DESCRIPTION
**Pull request by dpford**
NOTE: There is a complementary sheer PR that should be merged at the same time as this one: https://github.com/cfpb/sheer/pull/88

Facets are deprecated in ElasticSearch and will be removed in a future release. This migrates them to aggregations which work pretty much the same way as facets.

This PR essentially makes the change from {"term": "term-you-want"} to {"key": "term-you-want"} to reflect the minor difference between the ElasticSearch results for facets and aggregations.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1: Don't know much about the background behind these but it looks good to me

**Comment by willbarton** [comment]
This looks good. I just merged https://github.com/cfpb/sheer/pull/88, so merging this so nothing breaks.

**Comment by jimmynotjim** [comment]
I think this just broke the branch. I'm now seeing 

`UndefinedError: 'dict object' has no attribute 'key'`

from 

```
File "/Users/[user]/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/jinja2/filters.py", line 265, in do_sort
return sorted(value, key=sort_func, reverse=reverse)
```

**Comment by dpford** [comment]
Yes, you need to update sheer as well.
